apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo
  namespace: nifi
  labels:
    app: mongo

spec:
  serviceName: "mongo"
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
        - image: mongo
          name: mongo
          resources: {}
          ports:
            - containerPort: 27017
      restartPolicy: Always
status: {}

---
# apiVersion: v1
# kind: Service
# metadata:
#   name: mongo-service
#   namespace: nifi 
# spec:
#   selector:
#     app: mongo
#   ports:
#     - protocol: TCP
#       name: "port"
#       port: 80  
#       targetPort: 8080

apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: nifi 
spec:
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    app: mongo  