apiVersion: v1
kind: Pod
metadata:
  name: zookeeper
  namespace: default
  labels:
    app: zookeeper 
spec:
  containers:
    - name: zookeeper
      image: bitnami/zookeeper:latest
      ports:
        - containerPort: 2181
      env:
        - name: ALLOW_ANONYMOUS_LOGIN
          value: "yes"

---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  namespace: default
spec:
  selector:
    app: zookeeper
  ports:
    - name: "2181"
      port: 2181
      targetPort: 2181
