---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zookeeper
  labels:
    name: zookeeper
    app: zookeeper
  annotations:
    app.kubernetes.io/name: zookeeper
    app.kubernetes.io/part-of: nifi

spec:
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      automountServiceAccountToken: false
      enableServiceLinks: false
      setHostnameAsFQDN: true
      dnsPolicy: ClusterFirstWithHostNet
      restartPolicy: Always      

      containers:
      - name: zookeeper
        image: docker.io/zookeeper:3.9
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 2181
          name: zk
        - containerPort: 8080
          name: http
        - containerPort: 7070
          name: metrics
        env:
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: ZOO_SERVERS
            value: "server.1=$(POD_IP):2888:3888;2181"
        envFrom:
          - configMapRef:
              name: zookeeper-configmap
              optional: false
        resources:
          requests:
            cpu: 200m
            memory: 500Mi
          limits:
            cpu: 200m
            memory: 500Mi
        volumeMounts:
          - mountPath: /data
            name: data
            subPath: data
          - mountPath: /datalog
            name: data
            subPath: datalog
          - mountPath: /conf
            name: data
            subPath: conf
      
      volumes:
        - name: data
          emptyDir:
            sizeLimit: 2Gi   