---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nifi
  labels:
    name: nifi
    app: nifi
  
spec:
  selector:
    matchLabels:
      app: nifi
  template:
    metadata:
      labels:
        app: nifi
    
    spec:
      automountServiceAccountToken: false
      enableServiceLinks: false
      setHostnameAsFQDN: true
      dnsPolicy: ClusterFirstWithHostNet
      restartPolicy: Always
      
      initContainers:
        - name: wait-for-zookeeper
          image: docker.io/busybox:1.36
          command:
          - sh
          - -c
          - |
            echo "Connecting to Zookeeper ${NIFI_ZK_CONNECT_STRING}"
            until nc -vzw 1 zookeeper 2181 ; do
              echo "Waiting for zookeeper to start"
              sleep 3
            done
          envFrom:
          - configMapRef:
              name: nifi-configmap
              optional: false
          resources:
            requests:
              cpu: 20m
              memory: 10Mi
            limits:
              cpu: 20m
              memory: 10Mi
      
      containers:
      - name: nifi
        image: docker.io/apache/nifi:1.25.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          name: http
        - containerPort: 11443
          name: cluster
        - containerPort: 8443
          name: https
        - containerPort: 6342
          name: cluster-lb
        env:
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP #Pod ip
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name #Pod name
          - name: NIFI_UI_BANNER_TEXT
            value: $(POD_NAME)
          - name: NIFI_WEB_HTTP_HOST
            value: $(POD_NAME)  
          - name: NIFI_CLUSTER_NODE_ADDRESS
            value: $(POD_NAME)
          - name: NIFI_REMOTE_INPUT_SOCKET_HOST
            value: $(POD_NAME)
          - name: NIFI_REMOTE_INPUT_HOST
            value: $(POD_NAME)
          - name: HOSTNAME
            value: $(POD_IP) #Pod ip as hostname
          - name: NODE_IDENTITY
            value: $(POD_NAME) #Pod name as identity
        envFrom:
          - configMapRef:
              name: nifi-configmap #Import NiFi configuration variables
              optional: false
        volumeMounts:
          - name: data
            mountPath: /opt/nifi/nifi-current/data
            subPath: data
            readOnly: false
          - name: data
            mountPath: /opt/nifi/nifi-current/keytool
            subPath: keytool
            readOnly: false
        resources:
          requests:
            cpu: 400m
            memory: 2Gi
          limits:
            cpu: 400m
            memory: 2Gi
        
      volumes:
        - name: data
          emptyDir:
            sizeLimit: 3Gi
